version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: signbank
      POSTGRES_USER: signbank
      POSTGRES_PASSWORD: signbank
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U signbank -d signbank"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      args:
        REPO_URL: https://github.com/Signbank/Global-signbank.git
        REPO_REF: master
    environment:
      DJANGO_SETTINGS_MODULE: signbank.settings
      APP_DIR: /app
      PORT: "3000"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./server_specific.py:/app/signbank/settings/server_specific.py:ro

volumes:
  db_data:
